services:
  # Web Service
  - type: web
    name: sanscan-app
    runtime: node
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sanscan-db
          property: connectionString
      - key: NODE_VERSION
        value: 20.11.0

databases:
  # PostgreSQL Database
  - name: sanscan-db
    plan: free
    databaseName: sanscan
    user: sanscan